# -*- coding: utf-8 -*-
"""Function_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CjDSgoO-VrDd-Qdm3F5lvuQ19QvzwOFW
"""

# Q.1- WA function to take a number as parameter and  print True if given number is even
#       else print False

def even_fun(number):
    if( number % 2 == 0):
        print("True ")
    else:
        print("False ")
number = int(input("Enter Number: "))
even_fun(number)

# Q.2- WA function to take list as parameter and print all numbers of given list which are
#       divisible by 11

def div_fun(number):
    for number in list1:
       if number % 11 == 0:
        print(number)
list1 = [11,56,48,33,88,49,22]
div_fun(list1)

# Q.3- WA function to take string as parameter
#       Check if string is palindrome or not
#       If palindrome return 1
#       if not palindrome return 0

def palin(str1):
    if str1[::-1] == str1:
        return 1
    else:
        return 0
str1 = input("Enter String: ")
palin(str1)

# Q.4- WA function to check if number is prime or not. Return True if number is prime and
#       false if number not prime.

def prime(num):
    idx = 2
    while(idx < (num)):
        if(num % idx) == 0:
            print("False")
            break
        idx += 1
    else:
        print("True")
num = int(input("Enter a Number : "))
prime(num)

# Q.5- WA function to take a string as parameter. Print its alternate characters starting
#       from 2nd character

def alter(str):
    print(str[1::2])
str = input("Enter String: ")
alter(str)

# Q.6- WA function to take dictionary as parameter. Print all keys of the dictionary

def dict(dictionary):
    for key in dictionary.keys():
       print(key)
dict1 = {'a':1,'b':2,'c':3,'d':4}
dict(dict1)

# Q.7- WA function to take a dictionary as parameter. Print value of key "name" if
#       key "rollno" is having value 100.

def name(dictionary):
  if 'rollno' in dictionary and dictionary['rollno'] == 100:
    print(dictionary.get('name'))
    print(dictionary.get('rollno'))
info = {'name':'Shruti','rollno':100}
name(info)

# Q.8- WA function to take list of strings as parameter and print all strings which have
#      character 's' 2 times

def character(str):
  for string in list1:
    if string.count('s') == 1:
      print(string)
list1 = ['rose','lotus','lily','orchid']
character(str)
list1.

# Q.9- WA function to take list of dictionaries. Print all dictionaries which contain key "id"

def id(list_dictionary):
  for dictionary in list_dictionary:
    if 'id' in dictionary:
      print(dictionary)

list_dictionary = [{'id':100,'name':'Shruti'},
                   {'id':101,'name':'Shagufta'},
                   {'name':'Alisha'},
                   {'id':103,'name':'Moha'}]
id(list_dictionary)